export default {
  //Login User Type
  LOGIN_USER_RESET: 'LOGIN_USER_RESET',
  LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
  //SearchBar 
  GET_SEARCH_REQUEST: 'GET_SEARCH_REQUEST',
  GET_SEARCH_SUCCESS: 'GET_SEARCH_SUCCESS',
  GET_SEARCH_FAILURE: 'GET_SEARCH_FAILURE',
  //Get User Profile Data
  GET_USER_PROFILE_DATA_REQUEST: 'GET_USER_PROFILE_DATA_REQUEST',
  GET_USER_PROFILE_DATA_SUCCESS: 'GET_USER_PROFILE_DATA_SUCCESS',
  GET_USER_PROFILE_DATA_FAILURE: 'GET_USER_PROFILE_DATA_FAILURE',
  //Register  user types
  REGISTER_USER_RESET: 'REGISTER_USER_RESET',
  REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',
  //Food preferences
  GET_FOOD_PREFRENCES_REQUEST: 'GET_FOOD_PREFRENCES_REQUEST',
  GET_FOOD_PREFRENCES_SUCCESS: 'GET_FOOD_PREFRENCES_SUCCESS',
  GET_FOOD_PREFRENCES_FAILURE: 'GET_FOOD_PREFRENCES_FAILURE',
  //User verfication
  VERIFY_USER_REQUEST: 'VERIFY_USER_REQUEST',
  //Get payment History
  GET_PAYMENT_HISTORY_REQUEST: 'GET_PAYMENT_HISTORY_REQUEST',
  GET_PAYMENT_HISTORY_SUCCESS: 'GET_PAYMENT_HISTORY_SUCCESS',
  GET_PAYMENT_HISTORY_FAILURE: 'GET_PAYMENT_HISTORY_FAILURE',
  //PeopleChoice
  GET_PEOPLE_CHOICE_REQUEST: 'GET_PEOPLE_CHOICE_REQUEST',
  GET_PEOPLE_CHOICE_SUCCESS: 'GET_PEOPLE_CHOICE_SUCCESS',
  GET_PEOPLE_CHOICE_FAILURE: 'GET_PEOPLE_CHOICE_FAILURE',
  //Get Brunei Food Awards
  GET_BRUNEI_FOOD_AWARDS_REQUEST: 'GET_BRUNEI_FOOD_AWARDS_REQUEST',
  GET_BRUNEI_FOOD_AWARDS_SUCCESS: 'GET_BRUNEI_FOOD_AWARDS_SUCCESS',
  GET_BRUNEI_FOOD_AWARDS_FAILURE: 'GET_BRUNEI_FOOD_AWARDS_FAILURE',
  //Get Awards For Resturant
  GET_RESTAURANT_AWARDS_REQUEST: 'GET_RESTAURANT_AWARDS',
  GET_RESTAURANT_AWARDS_SUCCESS: 'GET_RESTAURANT_AWARDS_SUCCESS',
  GET_RESTAURANT_AWARDS_FAILURE: 'GET_RESTAURANT_AWARDS_FAILURE',
  //Bfa Recommendations
  GET_BFA_RECOMMENDATION_REQUEST: 'GET_BFA_RECOMMENDATION_REQUEST',
  GET_BFA_RECOMMENDATION_SUCCESS: 'GET_BFA_RECOMMENDATION_SUCCESS',
  GET_BFA_RECOMMENDATION_FAILURE: 'GET_BFA_RECOMMENDATION_FAILURE',
  //Get All Promotions
  GET_PROMOTIONS_REQUEST: 'GET_PROMOTIONS_REQUEST',
  GET_PROMOTIONS_SUCCESS: 'GET_PROMOTIONS_SUCCESS',
  GET_PROMOTIONS_FAILURE: 'GET_PROMOTIONS_FAILURE',
  //Get What's New
  GET_WHATSNEW_REQUEST: 'GET_WHATSNEW_REQUEST',
  GET_WHATSNEW_SUCCESS: 'GET_WHATSNEW_SUCCESS',
  GET_WHATSNEW_FAILURE: 'GET_WHATSNEW_FAILURE',
  // ADD_Order
  ADD_ORDER_REQUEST: 'ADD_ORDER_REQUEST',
  ADD_ORDER_SUCCESS: 'ADD_ORDER_SUCCESS',
  ADD_ORDER_FAILURE: 'ADD_ORDER_FAILURE',
  //Get notification
  GET_NOTIFICATION_REQUEST:'GET_NOTIFICATION_REQUEST',
  GET_NOTIFICATION_SUCCESS:'GGET_NOTIFICATION_SUCCESS',
  GET_NOTIFICATION_FAILURE:'GET_NOTIFICATION_FAILURE',
  
  // get_Order list
  GET_ORDERS_REQUEST: 'GET_ORDERS_REQUEST',
  GET_ORDERS_SUCCESS: 'GET_ORDER_SUCCESS',
  GET_ORDERS_FAILURE: 'GET_ORDER_FAILURE',

  GET_ORDERS_HISTORY_REQUEST: 'GET_ORDERS_HISTORY_REQUEST',
  GET_ORDERS_HISTORY_SUCCESS: 'GET_ORDER_HISTORY_SUCCESS',
  GET_ORDERS_HISTORY_FAILURE: 'GET_ORDER_HISTORY_FAILURE',
  //GET USER CUSINE
  GET_CUSINE_REQUEST: 'GET_CUSINE_REQUEST',
  GET_CUSINE_SUCCESS: 'GET_CUSINE_SUCCESS',
  GET_CUSINE_FAILURE: 'GET_CUSINE_FAILURE',
  //PROMOTION CLICK
  PROMOTION_CLICK_REQUEST: 'PROMOTION_CLICK_REQUEST',
  PROMOTION_CLICK_SUCCESS: 'PROMOTION_CLICK_SUCCESS',
  PROMOTION_CLICK_FAILURE: 'PROMOTION_CLICK_FAILURE',
  //GET BFArECOMMENDATION
  GET_BFA_RECOMMENDATION_REQUEST: 'GET_BFA_RECOMMENDATION_REQUEST',
  GET_BFA_RECOMMENDATION_SUCCESS: 'GET_BFA_RECOMMENDATION_SUCCESS',
  GET_BFA_RECOMMENDATION_FAILURE: 'GET_BFA_RECOMMENDATION_FAILURE',
  //GET RESTAURANT ALL DISHES
  GET_RESTAURANT_ALL_DISHES_REQUEST: 'GET_RESTAURANT_ALL_DISHES_REQUEST',
  GET_RESTAURANT_ALL_DISHES_SUCCESS: 'GET_RESTAURANT_ALL_DISHES_SUCCESS',
  GET_RESTAURANT_ALL_DISHES_FAILURE: 'GET_RESTAURANT_ALL_DISHES_FAILURE',
  //GET MORE_ABOUT_DISHES ALL DISHES
  GET_MORE_ABOUT_DISHES_REQUEST: 'GET_MORE_ABOUT_DISHES_REQUEST',
  GET_MORE_ABOUT_DISHES_SUCCESS: 'GET_MORE_ABOUT_DISHES_SUCCESS',
  GET_MORE_ABOUT_DISHES_FAILURE: 'GET_MORE_ABOUT_DISHES_FAILURE',
  //GET User
  GET_USERS_BY_ID_REQUEST: 'GET_USERS_BY_ID_REQUEST',
  GET_USERS_BY_ID_SUCCESS: 'GET_USERS_BY_ID_SUCCESS',
  GET_USERS_BY_ID_FAILURE: 'GET_USERS_BY_ID_FAILURE',

  //BFA_PARTNERS_LIST
  GET_BFA_PARTNERS_REQUEST: 'GET_BFA_PARTNERS_REQUEST',
  GET_BFA_PARTNERS_SUCCESS: 'GET_BFA_PARTNERS_SUCCESS',
  GET_BFA_PARTNERS_FAILURE: 'GET_BFA_PARTNERS_FAILURE',
  //More from rest.
  MORE_FROM_RESTAURANT_REQUEST: 'MORE_FROM_RESTAURANT_REQUEST',
  MORE_FROM_RESTAURANT_SUCCESS: 'MORE_FROM_RESTAURANT_SUCCESS',
  MORE_FROM_RESTAURANT_FAILURE: 'MORE_FROM_RESTAURANT_FAILURE',
  //GET ADVERTISEMENT BANNER DATA
  GET_ADD_BANNER_DATA_REQUEST: 'GET_ADD_BANNER_DATA_REQUEST',
  GET_ADD_BANNER_DATA_SUCCESS: 'GET_ADD_BANNER_DATA_SUCCESS',
  GET_ADD_BANNER_DATA_FAILURE: 'GET_ADD_BANNER_DATA_FAILURE',
  //Apply_for_job
  GET_APPLY_FOR_JOB_REQUEST: 'GET_APPLY_FOR_JOB_REQUEST',
  GET_APPLY_FOR_JOB_SUCCESS: ' GET_APPLY_FOR_JOB_SUCCESS',
  GET_APPLY_FOR_JOB_FAILURE: 'GET_APPLY_FOR_JOB_FAILURE',
  //GET PROMO NEWS
  GET_PROMO_NEWS_REQUEST: 'GET_PROMO_NEWS_REQUEST',
  GET_PROMO_NEWS_SUCCESS: 'GET_PROMO_NEWS_SUCCESS',
  GET_PROMO_NEWS_FAILURE: 'GET_PROMO_NEWS_FAILURE',

  //get Promo Jobs
  GET_PROMO_JOBS_REQUEST: 'GET_PROMO_JOBS_REQUEST',
  GET_PROMO_JOBS_SUCCESS: 'GET_PROMO_JOBS_SUCCESS',
  GET_PROMO_JOBS_FAILURE: 'GET_PROMO_JOBS_FAILURE',

  //get Favorite
  GET_FAVORITE_REQUEST: 'GET_FAVORITE_REQUEST',
  GET_FAVORITE_SUCCESS: 'GET_FAVORITE_SUCCESS',
  GET_FAVORITE_FAILURE: 'GET_FAVORITE_FAILURE',

  //add favorite
  ADD_FAVORITE_REQUEST: 'ADD_FAVORITE_REQUEST',
  ADD_FAVORITE_SUCCESS: 'ADD_FAVORITE_SUCCESS',
  ADD_FAVORITE_FAILURE: 'ADD_FAVORITE_FAILURE',
  //Help center
  SEND_HELP_CENTER_REQUEST:'SEND_HELP_CENTER_REQUEST',
  SEND_HELP_CENTER_SUCCESS:'SEND_HELP_CENTER_SUCCESS',
  SEND_HELP_CENTER_FAILURE:'SEND_HELP_CENTER_FAILURE',
  //Remove favorite
  ON_REMOVE_FAVORITE_REQUEST: 'ON_REMOVE_FAVORITE_REQUEST',
  ON_REMOVE_FAVORITE_SUCCESS: 'ON_REMOVE_FAVORITE_SUCCESS',
  ON_REMOVE_FAVORITE_FAILURE: 'ON_REMOVE_FAVORITE_FAILURE',
  // //Get user categories types
  //Cart
  ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
  ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
  ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',
  RETRIVE_CART_REQUEST: 'RETRIVE_CART_REQUEST',
  RETRIVE_CART_SUCCESS: 'RETRIVE_CART_SUCCESS',

  REMOVE_FROM_CART_REQUEST: 'REMOVE_FROM_CART_REQUEST',
  REMOVE_FROM_CART_SUCCESS: 'REMOVE_FROM_CART_SUCCESS',
  REMOVE_FROM_CART_FAILURE: 'REMOVE_FROM_CART_FAILURE',
  //
  CHECKOUT_ORDER_REQUEST: 'CHECKOUT_ORDER_REQUEST',
  CHECKOUT_ORDER_SUCCESS: 'CHECKOUT_ORDER_SUCCESS',
  CHECKOUT_ORDER_FAILURE: 'CHECKOUT_ORDER_FAILURE',
  //GET RESTAURENT DETAIL
  GET_RESTAURENT_DETAIL_REQUEST: 'GET_RESTAURENT_DETAIL_REQUEST',
  GET_RESTAURENT_DETAIL_SUCCESS: 'GET_RESTAURENT_DETAIL_SUCCESS',
  GET_RESTAURENT_DETAIL_FAILURE: 'GET_RESTAURENT_DETAIL_FAILURE',
  //GET_ALL_FAVORITE_RESTAURANT
  GET_ALL_FAVORITE_RESTAURANT_REQUEST: 'GET_ALL_FAVORITE_RESTAURANT_REQUEST',
  GET_ALL_FAVORITE_RESTAURANT_SUCCESS: 'GET_ALL_FAVORITE_RESTAURANT_SUCCESS',
  GET_ALL_FAVORITE_RESTAURANT_FAILURE: 'GET_ALL_FAVORITE_RESTAURANT_FAILURE',
  //ADD_FAVORITE_RESTAURANT
  ADD_FAVORITE_RESTAURANT_REQUEST: 'ADD_FAVORITE_RESTAURANT_REQUEST',
  ADD_FAVORITE_RESTAURANT_SUCCESS: 'ADD_FAVORITE_RESTAURANT_SUCCESS',
  ADD_FAVORITE_RESTAURANT_FAILURE: 'ADD_FAVORITE_RESTAURANT_FAILURE',
  //REMOVE_FAVORITE_RESTAURANT
  REMOVE_FAVORITE_RESTAURANT_REQUEST: 'REMOVE_FAVORITE_RESTAURANT_REQUEST',
  REMOVE_FAVORITE_RESTAURANT_SUCCESS: 'REMOVE_FAVORITE_RESTAURANT_SUCCESS',
  REMOVE_FAVORITE_RESTAURANT_FAILURE: 'REMOVE_FAVORITE_RESTAURANT_FAILURE',
  //GetDishByCusineId
  GET_DISH_BY_CUSINE_ID_REQUEST: 'GET_DISH_BY_CUSINE_ID_REQUEST',
  GET_DISH_BY_CUSINE_ID_SUCCESS: 'GET_DISH_BY_CUSINE_ID_SUCCESS',
  GET_DISH_BY_CUSINE_ID_FAILURE: 'GET_DISH_BY_CUSINE_ID_FAILURE',

  //GetNearestRestaurantBranchesByLocation
  GET_NEAREST_RESTAURANT_REQUEST: 'GET_NEAREST_RESTAURANT_REQUEST',
  GET_NEAREST_RESTAURANT_SUCCESS: 'GET_NEAREST_RESTAURANT_SUCCESS',
  GET_NEAREST_RESTAURANT_FAILURE: 'GET_NEAREST_RESTAURANT_FAILURE',

  //GetAreaAllForRandomizer
  GET_AREA_ALL_REQUEST:'GET_AREA_ALL_REQUEST',
  GET_AREA_ALL_SUCCESS:'GET_AREA_ALL_SUCCESS',
  GET_AREA_ALL_FAILURE:'GET_AREA_ALL_FAILURE',
  
  //GetAreaAllForRandomizer
  GET_PREMISE_ALL_REQUEST:'GET_PREMISE_ALL_REQUEST',
  GET_PREMISE_ALL_SUCCESS:'GET_PREMISE_ALL_SUCCESS',
  GET_PREMISE_ALL_FAILURE:'GET_PREMISE_ALL_FAILURE',
  
  //GetDistanceListForRandomiser
  GET_DISTANCE_LIST_REQUEST:'GET_DISTANCE_LIST_REQUEST',
  GET_DISTANCE_LIST_SUCCESS:'GET_DISTANCE_LIST_SUCCESS',
  GET_DISTANCE_LIST_FAILURE:'GET_DISTANCE_LIST_FAILURE',
  //GetAppliedJobs
  GET_APPLY_JOB_LIST_REQUEST:'GET_APPLY_JOB_LIST_REQUEST',
  GET_APPLY_JOB_LIST_SUCCESS:'GET_APPLY_JOB_LIST_SUCCESS',
  GET_APPLY_JOB_LIST_FAILURE:'GET_APPLY_JOB_LIST_FAILURE',
 // GetAllReviews
 GET_ALL_REVIEWS_LIST_REQUEST:'GET_ALL_REVIEWS_LIST_REQUEST',
 GET_ALL_REVIEWS_LIST_SUCCESS:'GET_ALL_REVIEWS_LIST_SUCCESS',
 GET_ALL_REVIEWS_LIST_FAILURE:'GET_ALL_REVIEWS_LIST_FAILURE',


  //GetUserRandomiserById
  GET_USER_RANDOMISER_SETTING_REQUEST:'GET_USER_RANDOMISER_SETTING_REQUEST',
  GET_USER_RANDOMISER_SETTING_SUCCESS:'GET_USER_RANDOMISER_SETTING_SUCCESS',
  GET_USER_RANDOMISER_SETTING_FAILURE:'GET_USER_RANDOMISER_SETTING_FAILURE',

   //GetUserRandomiserById
   GET_BALI_COINS_REQUEST:'GET_BALI_COINS_REQUEST',
   GET_BALI_COINS_SUCCESS:'GET_BALI_COINS_SUCCESS',
   GET_BALI_COINS_FAILURE:'GET_BALI_COINS_FAILURE',

  SET_THEME:'SET_THEME',



  // Get user categories types
  // GET_USER_CATS_RESET: "GET_USER_CATS_RESET",
  //GET_USER_CATS_REQUEST: 'GET_USER_CATS_REQUEST',
  // GET_USER_CATS_SUCCESS: "GET_USER_CATS_SUCCESS",
  // GET_USER_CATS_FAILURE: "GET_USER_CATS_FAILURE",

  // //Get user categories types
  // CATS_WITH_PRODUCTS_RESET: "CATS_WITH_PRODUCTS_RESET",
  // CATS_WITH_PRODUCTS_REQUEST: "CATS_WITH_PRODUCTS_REQUEST",
  // CATS_WITH_PRODUCTS_SUCCESS: "CATS_WITH_PRODUCTS_SUCCESS",
  // CATS_WITH_PRODUCTS_FAILURE: "CATS_With_PRODUCTS_FAILURE",

  // //Add user category types
  // ADD_PRODUCT_CAT_RESET: "ADD_PRODUCT_CAT_RESET",
  // ADD_PRODUCT_CAT_REQUEST: "ADD_PRODUCT_CAT_REQUEST",
  // ADD_PRODUCT_CAT_SUCCESS: "ADD_PRODUCT_CAT_SUCCESS",
  // ADD_PRODUCT_CAT_FAILURE: "ADD_PRODUCT_CAT_FAILURE",

  // //Delete user category types
  // DELETE_PRODUCT_CAT_RESET: "DELETE_PRODUCT_CAT_RESET",
  // DELETE_PRODUCT_CAT_REQUEST: "DELETE_PRODUCT_CAT_REQUEST",
  // DELETE_PRODUCT_CAT_SUCCESS: "DELETE_PRODUCT_CAT_SUCCESS",
  // DELETE_PRODUCT_CAT_FAILURE: "DELETE_PRODUCT_CAT_FAILURE",

  // //Forget password types
  // FORGET_PASSWORD_RESET: "FORGET_PASSWORD_RESET",
  // FORGET_PASSWORD_REQUEST: "FORGET_PASSWORD_REQUEST",
  // FORGET_PASSWORD_SUCCESS: "FORGET_PASSWORD_SUCCESS",
  // FORGET_PASSWORD_FAILURE: "FORGET_PASSWORD_FAILURE",

  // //Get site data by url types
  // GET_SITE_DATA_RESET: "GET_SITE_DATA_RESET",
  // GET_SITE_DATA_REQUEST: "GET_SITE_DATA_REQUEST",
  // GET_SITE_DATA_SUCCESS: "GET_SITE_DATA_SUCCESS",
  // GET_SITE_DATA_FAILURE: "GET_SITE_DATA_FAILURE",

  // //Save site for user types
  // SAVE_SITE_RESET: "SAVE_SITE_RESET",
  // SAVE_SITE_REQUEST: "SAVE_SITE_REQUEST",
  // SAVE_SITE_SUCCESS: "SAVE_SITE_SUCCESS",
  // SAVE_SITE_FAILURE: "SAVE_SITE_FAILURE",

  // //Update site for user types
  // UPDATE_SITE_RESET: "UPDATE_SITE_RESET",
  // UPDATE_SITE_REQUEST: "UPDATE_SITE_REQUEST",
  // UPDATE_SITE_SUCCESS: "UPDATE_SITE_SUCCESS",
  // UPDATE_SITE_FAILURE: "UPDATE_SITE_FAILURE",

  // //Delete site for user types
  // DELETE_SITE_RESET: "DELETE_SITE_RESET",
  // DELETE_SITE_REQUEST: "DELETE_SITE_REQUEST",
  // DELETE_SITE_SUCCESS: "DELETE_SITE_SUCCESS",
  // DELETE_SITE_FAILURE: "DELETE_SITE_FAILURE",

  // //Get user saved sites by uuid types
  // GET_SAVED_SITES_RESET: "GET_SAVED_SITES_RESET",
  // GET_SAVED_SITES_REQUEST: "GET_SAVED_SITES_REQUEST",
  // GET_SAVED_SITES_SUCCESS: "GET_SAVED_SITES_SUCCESS",
  // GET_SAVED_SITES_FAILURE: "GET_SAVED_SITES_FAILURE",

  // //Get all notifications of the user
  // GET_NOTIFICATIONS_RESET: "GET_NOTIFICATIONS_RESET",
  // GET_NOTIFICATIONS_REQUEST: "GET_NOTIFICATIONS_REQUEST",
  // // UPDATE_NOTIFICATION_REQUEST:"UPDATE_NOTIFICATION_REQUEST",
  // GET_NOTIFICATIONS_SUCCESS: "GET_NOTIFICATIONS_SUCCESS",
  // GET_NOTIFICATIONS_FAILURE: "GET_NOTIFICATIONS_FAILURE",
};
