export default {
//Login User Type
LOGIN_USER_RESET: "LOGIN_USER_RESET",
LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",

  //Register  user types
  REGISTER_USER_RESET: "REGISTER_USER_RESET",
  REGISTER_USER_REQUEST: "REGISTER_USER_REQUEST",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE",

  //Get Awards For Resturant
  GET_RESTAURANT_AWARDS_REQUEST:'GET_RESTAURANT_AWARDS',
  GET_RESTAURANT_AWARDS_SUCCESS:'GET_RESTAURANT_AWARDS_SUCCESS',
  GET_RESTAURANT_AWARDS_FAILURE:'GET_RESTAURANT_AWARDS_FAILURE',


  //GET USER CUSINE 
  GET_CUSINE_REQUEST:'GET_CUSINE_REQUEST',
  GET_CUSINE_SUCCESS:'GET_CUSINE_SUCCESS',
  GET_CUSINE_FAILURE:'GET_CUSINE_FAILURE',


  //GET RESTAURANT ALL DISHES
  GET_RESTAURANT_ALL_DISHES_REQUEST:'GET_RESTAURANT_ALL_DISHES_REQUEST',
  GET_RESTAURANT_ALL_DISHES_SUCCESS:'GET_RESTAURANT_ALL_DISHES_SUCCESS',
  GET_RESTAURANT_ALL_DISHES_FAILURE:'GET_RESTAURANT_ALL_DISHES_FAILURE',
  
//GET User
GET_USERS_BY_ID_REQUEST:'GET_USERS_BY_ID_REQUEST',
GET_USERS_BY_ID_SUCCESS:'GET_USERS_BY_ID_SUCCESS',
GET_USERS_BY_ID_FAILURE:'GET_USERS_BY_ID_FAILURE',



//BFA_PARTNERS_LIST
GET_BFA_PARTNERS_REQUEST:'GET_BFA_PARTNERS_REQUEST',
GET_BFA_PARTNERS_SUCCESS:'GET_BFA_PARTNERS_SUCCESS',
GET_BFA_PARTNERS_FAILURE:'GET_BFA_PARTNERS_FAILURE',


//GET ADVERTISEMENT BANNER DATA
GET_ADD_BANNER_DATA_REQUEST:'GET_ADD_BANNER_DATA_REQUEST',
GET_ADD_BANNER_DATA_SUCCESS:'GET_ADD_BANNER_DATA_SUCCESS',
GET_ADD_BANNER_DATA_FAILURE:'GET_ADD_BANNER_DATA_FAILURE',

  // //Get user categories types
  // GET_USER_CATS_RESET: "GET_USER_CATS_RESET",
  // GET_USER_CATS_REQUEST: "GET_USER_CATS_REQUEST",
  // GET_USER_CATS_SUCCESS: "GET_USER_CATS_SUCCESS",
  // GET_USER_CATS_FAILURE: "GET_USER_CATS_FAILURE",

  // //Get user categories types
  // CATS_WITH_PRODUCTS_RESET: "CATS_WITH_PRODUCTS_RESET",
  // CATS_WITH_PRODUCTS_REQUEST: "CATS_WITH_PRODUCTS_REQUEST",
  // CATS_WITH_PRODUCTS_SUCCESS: "CATS_WITH_PRODUCTS_SUCCESS",
  // CATS_WITH_PRODUCTS_FAILURE: "CATS_With_PRODUCTS_FAILURE",

  // //Add user category types
  // ADD_PRODUCT_CAT_RESET: "ADD_PRODUCT_CAT_RESET",
  // ADD_PRODUCT_CAT_REQUEST: "ADD_PRODUCT_CAT_REQUEST",
  // ADD_PRODUCT_CAT_SUCCESS: "ADD_PRODUCT_CAT_SUCCESS",
  // ADD_PRODUCT_CAT_FAILURE: "ADD_PRODUCT_CAT_FAILURE",

  // //Delete user category types
  // DELETE_PRODUCT_CAT_RESET: "DELETE_PRODUCT_CAT_RESET",
  // DELETE_PRODUCT_CAT_REQUEST: "DELETE_PRODUCT_CAT_REQUEST",
  // DELETE_PRODUCT_CAT_SUCCESS: "DELETE_PRODUCT_CAT_SUCCESS",
  // DELETE_PRODUCT_CAT_FAILURE: "DELETE_PRODUCT_CAT_FAILURE",

  // //Forget password types
  // FORGET_PASSWORD_RESET: "FORGET_PASSWORD_RESET",
  // FORGET_PASSWORD_REQUEST: "FORGET_PASSWORD_REQUEST",
  // FORGET_PASSWORD_SUCCESS: "FORGET_PASSWORD_SUCCESS",
  // FORGET_PASSWORD_FAILURE: "FORGET_PASSWORD_FAILURE",

  // //Get site data by url types
  // GET_SITE_DATA_RESET: "GET_SITE_DATA_RESET",
  // GET_SITE_DATA_REQUEST: "GET_SITE_DATA_REQUEST",
  // GET_SITE_DATA_SUCCESS: "GET_SITE_DATA_SUCCESS",
  // GET_SITE_DATA_FAILURE: "GET_SITE_DATA_FAILURE",

  // //Save site for user types
  // SAVE_SITE_RESET: "SAVE_SITE_RESET",
  // SAVE_SITE_REQUEST: "SAVE_SITE_REQUEST",
  // SAVE_SITE_SUCCESS: "SAVE_SITE_SUCCESS",
  // SAVE_SITE_FAILURE: "SAVE_SITE_FAILURE",

  // //Update site for user types
  // UPDATE_SITE_RESET: "UPDATE_SITE_RESET",
  // UPDATE_SITE_REQUEST: "UPDATE_SITE_REQUEST",
  // UPDATE_SITE_SUCCESS: "UPDATE_SITE_SUCCESS",
  // UPDATE_SITE_FAILURE: "UPDATE_SITE_FAILURE",

  // //Delete site for user types
  // DELETE_SITE_RESET: "DELETE_SITE_RESET",
  // DELETE_SITE_REQUEST: "DELETE_SITE_REQUEST",
  // DELETE_SITE_SUCCESS: "DELETE_SITE_SUCCESS",
  // DELETE_SITE_FAILURE: "DELETE_SITE_FAILURE",

  // //Get user saved sites by uuid types
  // GET_SAVED_SITES_RESET: "GET_SAVED_SITES_RESET",
  // GET_SAVED_SITES_REQUEST: "GET_SAVED_SITES_REQUEST",
  // GET_SAVED_SITES_SUCCESS: "GET_SAVED_SITES_SUCCESS",
  // GET_SAVED_SITES_FAILURE: "GET_SAVED_SITES_FAILURE",

  // //Get all notifications of the user
  // GET_NOTIFICATIONS_RESET: "GET_NOTIFICATIONS_RESET",
  // GET_NOTIFICATIONS_REQUEST: "GET_NOTIFICATIONS_REQUEST",
  // // UPDATE_NOTIFICATION_REQUEST:"UPDATE_NOTIFICATION_REQUEST",
  // GET_NOTIFICATIONS_SUCCESS: "GET_NOTIFICATIONS_SUCCESS",
  // GET_NOTIFICATIONS_FAILURE: "GET_NOTIFICATIONS_FAILURE",
};
