export const routeName = {
  SPLASH: 'SPLASH',
  LOGIN: 'LOGIN',
  SIGN_UP: 'SIGN_UP',
  LANDING_SCREEN: 'LANDING_SCREEN',
  Categories :'Categories',
  RestaurantBranch :'RESTAURANT_BRANCH',
  DishDetails:'DishDetails',
  MAP_VIEW:"MAP_VIEW",
  MENU:"MENU",
  // BOTTOM TABS
  HOME_BOTTOM: "Home",
  RANDOMISER_BOTTOM: "Randomiser",
  PROMOS_BOTTOM: "Feed",
  CHECK_OUT_BOTTOM: "Checkout",
  MORE_BOTTOM: "More",
  DISH_DETAIL:"DISH_DETAIL",
  RestaurantDetail:"RestaurantDetail",
  FeaturedSearch:"FeaturedSearch",
  SearchAll:'SearchAll',
  MAP_VIEW:'MAP_VIEW',
  FilterSearch:'FilterSearch',
  PROFILE_SCREEN:'PROFILE_SCREEN',
  ORDER_HISTORY:'ORDER_HISTORY',
  SELECT_COISINES:' SELECT_COISINES',
  APPLY_JOBS:'APPLY_JOBS',
  ADD_TO_CART:"ADD_TO_CART",
  TRANSACTION_HISTORY:"TRANSACTION_HISTORY",
  RANDOMISER_RESULT:'RANDOMISER_RESULT'
};
